# game setup
WIDTH = 300
HEIGHT = 300
FPS = 60
INPUT = 'ps4'
CONTROLLER_DEADZONE = 0.3


TILESIZE = 20
WALL_WIDTH = 20

FOOTSTEP_DISTANCE = 50
FOOTSTEP_VOLUME = 7


SOUNDBEAM_FORCE = 8
SOUNDBEAM_RADIUS = 1
SOUNDBEAM_SIZE = 1
SOUNDBEAM_SIZE_GAIN = 10
SOUNDBEAM_NUMBERS = 128
SOUNDBEAM_SPEED = 4
SOUNDBEAM_ATTENUATION = 20
SOUNDBEAM_MAX_LOUDNESS = 20
SOUNDBEAM_RADIUS_GAIN = 10

COLLISION_TYPES = {
    "soundbeam": 1,
    "obstacle": 2,
}

OBJECT_CATEGORIES = {
    "soundbeam":   0b01,
    "obstacle":    0b10,
}

CATEGORY_MASKS = {
    "soundbeam":   0b10,
    "obstacle":    0b11,
}
